//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpMe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolEntities2 : DbContext
    {
        public SchoolEntities2()
            : base("name=SchoolEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Audition> Audition { get; set; }
        public virtual DbSet<DateNow> DateNow { get; set; }
        public virtual DbSet<Discipline> Discipline { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Lesson> Lesson { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<Timetable> Timetable { get; set; }
        public virtual DbSet<TypeOfLesson> TypeOfLesson { get; set; }
    }
}
