//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpMe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public int ID_Timetable { get; set; }
        public Nullable<int> Teacher { get; set; }
        public Nullable<int> Lesson { get; set; }
        public Nullable<int> Groups { get; set; }
        public Nullable<int> Discipline { get; set; }
        public Nullable<int> TypeOfLesson { get; set; }
        public Nullable<int> Audition { get; set; }
        public Nullable<int> DateNow { get; set; }
    
        public virtual Audition Audition1 { get; set; }
        public virtual DateNow DateNow1 { get; set; }
        public virtual Discipline Discipline1 { get; set; }
        public virtual Groups Groups1 { get; set; }
        public virtual Lesson Lesson1 { get; set; }
        public virtual Teacher Teacher1 { get; set; }
        public virtual TypeOfLesson TypeOfLesson1 { get; set; }
    }
}
